# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Install SUDO
          command: 'apt-get update && apt-get install -y sudo'
      - run:
          name: Install GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Doxygen
          command: 'apt-get update && sudo apt-get install -y doxygen'
      - run:
          name: Install Graphviz
          command: 'apt-get update && sudo apt-get install -y graphviz'
      - run:
          name: Configure CMake
          command: 'cmake -Bbuild'
      - run:
          name: Build
          command: 'cmake --build build'
      - run:
          name: Test
          working_directory: build
          command: 'ctest'