name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [x86, x64]
        os: [ ubuntu-latest, windows-latest ] # [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: '${{ matrix.os }}'
    
    name: '${{ matrix.os }}-${{ matrix.platform }}: build'

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Required Software
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          apt-get update
          apt-get install cmake doxygen graphviz
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install cmake doxygen.install graphviz
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DDOXYGEN_GENERATE=false
      shell: bash

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build
      shell: bash
      
    - name: Test
      run: |
        ctest
      shell: bash
      working-directory: ${{github.workspace}}/build
